INSERT INTO days (name) VALUES ('ПН');
INSERT INTO days (name) VALUES ('ВТ');
INSERT INTO days (name) VALUES ('СР');
INSERT INTO days (name) VALUES ('ЧТ');
INSERT INTO days (name) VALUES ('ПТ');
INSERT INTO days (name) VALUES ('СБ');
INSERT INTO days (name) VALUES ('ВС');
---------------------------------------------------------
INSERT INTO times (name) VALUES ('08.50-10.25');
INSERT INTO times (name) VALUES ('10.40-12.15');
INSERT INTO times (name) VALUES ('13.15-14.50');
INSERT INTO times (name) VALUES ('15.00-16.35');
INSERT INTO times (name) VALUES ('16.45-18.20');
INSERT INTO times (name) VALUES ('18.30-20.05');
----------------------------------------------------------
INSERT INTO groups (name) VALUES ('group 520-1');
INSERT INTO groups (name) VALUES ('group 526-1');
INSERT INTO groups (name) VALUES ('group 526-2');
INSERT INTO groups (name) VALUES ('group 527-1');
INSERT INTO groups (name) VALUES ('group 527-2');
----------------------------------------------------------
INSERT INTO rooms (name) VALUES ('лаб. 401 ф');
INSERT INTO rooms (name) VALUES ('лек. ауд. 412 ф');
INSERT INTO rooms (name) VALUES ('лаб. 407 ф');
INSERT INTO rooms (name) VALUES ('лаб. 409 ф');
INSERT INTO rooms (name) VALUES ('лек. ауд. 421 ф');
INSERT INTO rooms (name) VALUES ('ауд. 230 ф');
INSERT INTO rooms (name) VALUES ('ауд. 217 ф');
----------------------------------------------------------
INSERT INTO subjects (name) VALUES ('Математика (лекция)');
INSERT INTO subjects (name) VALUES ('КОИБАС (лекция)');
INSERT INTO subjects (name) VALUES ('ПОИБ (лекция)');
INSERT INTO subjects (name) VALUES ('ТСИМЗИ (лекция)');
INSERT INTO subjects (name) VALUES ('ООИБ (лекция)');
INSERT INTO subjects (name) VALUES ('Дискретная Математика (лекция)');
INSERT INTO subjects (name) VALUES ('КМЗИ (лекция)');
INSERT INTO subjects (name) VALUES ('Информатика (лекция)');
INSERT INTO subjects (name) VALUES ('КОИБАС (практика)');
INSERT INTO subjects (name) VALUES ('ПОИБ (практика)');
INSERT INTO subjects (name) VALUES ('Математика (практика)');
INSERT INTO subjects (name) VALUES ('ТСИМЗИ (практика)');
INSERT INTO subjects (name) VALUES ('ООИБ (практика)');
INSERT INTO subjects (name) VALUES ('Дискретная Математика (практика)');
INSERT INTO subjects (name) VALUES ('КМЗИ (практика)');
INSERT INTO subjects (name) VALUES ('Информатика (практика)');
----------------------------------------------------------
INSERT INTO teachers (name) VALUES ('Сопов М. А.');
INSERT INTO teachers (name) VALUES ('Конев А. А.');
INSERT INTO teachers (name) VALUES ('Афонин Г. И.');
INSERT INTO teachers (name) VALUES ('Давыдова Е. М.');
INSERT INTO teachers (name) VALUES ('Кручинин Д. В.');
INSERT INTO teachers (name) VALUES ('Евсютин О. О.');
INSERT INTO teachers (name) VALUES ('Черных Д. В.');
INSERT INTO teachers (name) VALUES ('Костюченко Е. Ю.');
INSERT INTO teachers (name) VALUES ('Мельников М. И.');
/*----------------------------------------------------------
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (3, 1, 1, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (4, 1, 2, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (5, 1, 3, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (6, 1, 4, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (7, 1, 5, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (8, 1, 6, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (9, 2, 1, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (10, 2, 2, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (11, 2, 3, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (12, 2, 4, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (13, 2, 5, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (14, 2, 6, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (15, 3, 1, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (16, 4, 1, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (17, 5, 1, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (19, 6, 1, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (20, 3, 2, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (21, 3, 3, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (22, 3, 4, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (23, 3, 5, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (24, 3, 6, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (25, 4, 2, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (26, 4, 3, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (27, 4, 4, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (28, 4, 5, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (29, 4, 6, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (30, 5, 2, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (31, 5, 3, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (33, 5, 4, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (34, 5, 5, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (35, 5, 6, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (36, 6, 2, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (37, 6, 3, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (38, 6, 4, 1);
INSERT INTO days_times (id, id_days, id_times, weight) VALUES (39, 6, 5, 1);
----------------------------------------------------------
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (1, 3, 6, 1);
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (2, 3, 14, 1);
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (3, 3, 7, 1);
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (5, 3, 15, 1);
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (6, 3, 10, 1);
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (7, 3, 19, 2);
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (8, 4, 20, 2);
INSERT INTO groups_subjects (id, id_groups, id_subjects, weight) VALUES (10, 4, 7, 2);
----------------------------------------------------------
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (17, 1, 14);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (18, 1, 15);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (19, 1, 16);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (20, 1, 17);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (21, 1, 18);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (22, 1, 19);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (23, 1, 20);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (24, 1, 21);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (9, 2, 5);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (10, 2, 6);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (11, 2, 7);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (12, 2, 8);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (13, 2, 9);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (14, 2, 10);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (15, 2, 11);
INSERT INTO rooms_subjects (id, id_rooms, id_subjects) VALUES (16, 2, 12);
----------------------------------------------------------
INSERT INTO teachers_subjects (id, id_teachers, id_subjects, weight) VALUES (4, 2, 15, 4);
INSERT INTO teachers_subjects (id, id_teachers, id_subjects, weight) VALUES (5, 2, 7, 4);
INSERT INTO teachers_subjects (id, id_teachers, id_subjects, weight) VALUES (6, 7, 11, 4);
INSERT INTO teachers_subjects (id, id_teachers, id_subjects, weight) VALUES (7, 7, 20, 4);*/